# Generated by Django 3.2.4 on 2021-08-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='descripcion',
        ),
    ]
