# Generated by Django 3.2.4 on 2021-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default=None, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
