# Generated by Django 3.2.4 on 2021-07-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210703_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.subasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.usuario')),
            ],
        ),
    ]
