# Generated by Django 3.2.4 on 2021-07-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_ganada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='subastas',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='subasta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.subasta'),
            preserve_default=False,
        ),
    ]
