# Generated by Django 3.2.4 on 2021-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210705_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='subastas'),
        ),
    ]
